pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '80453a0e-abfa-4d89-8dfa-a4a395253ba7', 
                url: 'https://github.com/yasirziaaulakh/Jenkins-Zero-To-Hero',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    cd python-jenkins-argocd-k8s
                    echo 'Buid Docker Image'
                    docker build -t yasirzia/todo-app:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                     sh '''
            echo 'Logging in to Docker'
            echo "Pakistan42@" | docker login -u "yasirzia" --password-stdin
            '''
                    sh '''
                    echo 'Push to Repo'
                    docker push yasirzia/todo-app:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
               git credentialsId: '80453a0e-abfa-4d89-8dfa-a4a395253ba7', 
                url: 'https://github.com/yasirziaaulakh/Jenkins-Zero-To-Hero',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: '80453a0e-abfa-4d89-8dfa-a4a395253ba7', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                         sh '''
                cd python-jenkins-argocd-k8s/deploy
                echo "Current deploy.yaml content:"
                cat deploy.yaml

                # Update the image tag with the build number
                sed -i "s/yasirzia\/todo-app:.*/yasirzia\/todo-app:${BUILD_NUMBER}/" deploy.yaml

                echo "Updated deploy.yaml content:"
                cat deploy.yaml

                # Git operations
                git config --global user.email "yasirzia4@gmail.com"  # Update with your email
                git config --global user.name "${GIT_USERNAME}"

                git add deploy.yaml
                git commit -m "Updated deploy.yaml with build number ${BUILD_NUMBER} | Jenkins Pipeline"

                # Push changes to the repository
                git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/yasirziaaulakh/Jenkins-Zero-To-Hero HEAD:main
                
                        '''                        
                    }
                }
            }
        }
    }
}
